keys:
  - &admin_dev age1394575g5xn5g0gm6v2jhgwv7cpdnvrg9uqa0e4w80dsx5qkmt9lqvgmy4l
  - &server_supervisor age1kqt6gwq9arqxmwerv2g70u65nankew9kheretyr4epw6zq9ucuaqjcemjj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_dev
        - *server_supervisor
